@startuml
left to right direction
scale 1.8
title Diagramme de cas d'utilisation - Chefchaouen Bleu Durable

actor "Visiteur" as Visiteur
actor "Administrateur" as Admin
actor "Editeur" as Editeur

Admin <|-- Editeur

rectangle "Blog : Chefchaouen - Bleu Durable" {
  (Consulter la liste des articles) as UC1
  (Voir les détails d'un article) as UC2
  (Rechercher / filtrer un article) as UC3
  (Commenter / Liker / Sauvegarder un article) as UC4
  (Partager un article) as UC5
  (Gérer les articles) as UC6
  (Gérer les utilisateurs) as UC7
}

' Relations du Visiteur
Visiteur -- UC1
Visiteur -- UC2
Visiteur -- UC3
Visiteur -- UC4
Visiteur -- UC5

' Relations de l'Editeur
Editeur -- UC6

' Relations de l'Administrateur
Admin -- UC7

@enduml
